### ISSUE TITLE
Mogelijk worden niet-bestaande externe programma's aangeroepen

### ISSUE THREAD

**Issue by bcollin** [maartenoosterhoff/gwbasic-memories#4]
Ik kwam in de broncode van twee adventures de aanroep van externe programma's tegen die niet worden mee verspreid. 

Het is mij onduidelijk wat deze instructies doen en of ze wellicht programma's aanroepen die standaard onderdeel van GW Basic of PC Basic zijn. 

Het kan dus zijn dat dit gewoon doet wat het moet doen, maar het kwam wat vreemd over.

Het gaat om de volgende programma's en de bijbehorende regels. 

LANDUSIE.ASC: 

`130 RUN "D:\BASIC\BP.BAS"`

`4510 IF C1*C2=192 THEN PRINT "Het is u gelukt , GEFELICITEERD !";INPUT$(1):RUN"D:\BASIC\BP.BAS"`

NEFRE.ASC:

`350 RUN "D:\BASIC\BP.BAS"`

`470 RUN "D:\BASIC\BP.BAS"`

**Comment by maartenoosterhoff** [comment]
BP.BAS is een verwijzing naar een menu programma wat ik destijds had. Dit is in de huidige context niet meer correct, en kan verwijderd worden.
